# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('token', models.CharField(blank=True, default='', max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, default='', max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('lastName',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('numberPeopleNeeded', models.IntegerField(default=0)),
                ('numberPeopleAccepted', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('startDate',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('token', models.CharField(blank=True, default='', max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(blank=True, default='', max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('lastName',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(to='server.UserModel'),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobEmployer', to='server.EmployerModel'),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(to='server.Tag'),
        ),
    ]
