# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170708_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(related_name='jobEmployee', to='server.UserModel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='postDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
