# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170708_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employermodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employermodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employermodel',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
