# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170708_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tagName',)},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='iconName',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='jobEmployee', to='server.UserModel'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
