# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170708_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employees',
        ),
        migrations.AddField(
            model_name='job',
            name='employeesAccepted',
            field=models.ManyToManyField(blank=True, related_name='employeesAccepted', to='server.UserModel'),
        ),
        migrations.AddField(
            model_name='job',
            name='employeesPending',
            field=models.ManyToManyField(blank=True, related_name='employeesPending', to='server.UserModel'),
        ),
    ]
