# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170708_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='jobsDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
