# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170708_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
