# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
