# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_usermodel_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employermodel',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
