# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20170725_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermodel',
            name='accountBalance',
            field=models.FloatField(default=0),
        ),
    ]
